name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Se ejecuta cada vez que subes algo a main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          # Aquí mapeas el secreto de GitHub a la variable que usa tu código
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # La carpeta que genera Vite
          branch: gh-pages # La rama donde se sube el resultado
